Convert "Items of concern" (留意事項) to requirements syntax
metanorma/mn-samples-plateau pull request #126
Opened 2024-07-27 18:06 UTC by anermina

Closes https://github.com/metanorma/mn-samples-plateau/issues/121.

2024-07-28 01:15 UTC, ronaldtse requested changes
Thanks @anermina , just need to fix block type.

2024-07-28 01:15 UTC, ronaldtse commented on sources/002-v4/sections/section-05/section-04.adoc
> +[requirements]
It should be “requirement” not “requirements”.

2024-07-28 09:45 UTC, anermina commented
> Thanks @anermina , just need to fix block type.

Thank you @ronaldtse, this is now fixed.

2024-07-28 10:10 UTC, ronaldtse commented
Thanks. I've also decided to change to use the URI path `att` for "points of attention".

The problem right now is that these crash Metanorma (ping @opoudjis ):

```
[requirement]
.拡張製品仕様書に含めることが望ましい地物型等について
====
[%metadata]
identifier:: /att/decision/1
subject:: 3D都市モデル
statement:: 拡張製品仕様書に含めることが望ましい地物型
+
--
* 「拡張製品仕様書に含めることが望ましい地物型とLODの組み合わせ」（<<tab-1-1>>）として「基本セット」に含まれる「建築物」、「道路」、「都市計画決定情報」、「土地利用」、「災害リスク」及び「地形」の各地物型は、ユースケースの利用有無によらず、3D都市モデルに含むことが望ましい。

* これらの地物型に定義された地物属性のうち、主題属性（名称や種類、面積など、図形以外の属性）について、拡張製品仕様書に含むことが望ましい主題属性を「Annex A拡張製品仕様のための様式」の「取得項目一覧」に示す。

* 拡張製品仕様書に含むべき地物型等の選定においては、「取得項目一覧」を参考にすること。
--
====
```

Error:
```
<dt>statement</dt>
Fatal Error: undefined local variable or method `e' for an instance of Metanorma::Requirements::Default
mn-requirements-0.3.7/lib/metanorma/default/cleanup.rb:140:in `reqt_dl_to_classif2': undefined local variable or method `e' for an instance of Metanorma::Requirements::Default (NameError)

        val = term.at("./following::dd/p") || e.at("./following::dd")
                                              ^
	from mn-requirements-0.3.7/lib/metanorma/default/cleanup.rb:134:in `block in reqt_dl_to_classif1'
```

2024-07-28 10:10 UTC, ronaldtse commented
Changing it into this doesn't crash:
```adoc
[requirement]
.拡張製品仕様書に含めることが望ましい地物型等について
====
[%metadata]
identifier:: /att/decision/1
subject:: 3D都市モデル
statement:: 拡張製品仕様書に含めることが望ましい地物型
part:: 「拡張製品仕様書に含めることが望ましい地物型とLODの組み合わせ」（<<tab-1-1>>）として「基本セット」に含まれる「建築物」、「道路」、「都市計画決定情報」、「土地利用」、「災害リスク」及び「地形」の各地物型は、ユースケースの利用有無によらず、3D都市モデルに含むことが望ましい。
part:: これらの地物型に定義された地物属性のうち、主題属性（名称や種類、面積など、図形以外の属性）について、拡張製品仕様書に含むことが望ましい主題属性を「Annex A拡張製品仕様のための様式」の「取得項目一覧」に示す。
part::  拡張製品仕様書に含むべき地物型等の選定においては、「取得項目一覧」を参考にすること。
====
```

There is absolutely no error check on what actually goes wrong.

2024-07-28 10:52 UTC, ronaldtse commented
@opoudjis AsciiDoctor has no issue with such DL, this is an mn-requirements bug. Mucking with XML is *always* the incorrect solution. It's time to integrate mn-requirements with the [`ogc-modspec` gem](https://github.com/metanorma/ogc-modspec).

<img width="871" alt="Screenshot 2024-07-28 at 6 16 06 PM" src="https://github.com/user-attachments/assets/ef12f32f-8be6-4cfb-a1ac-fbb2e5760c0e">

2024-07-28 10:53 UTC, ronaldtse commented
@anermina Due to the bug discovered, please help do the following:

* for all the `statements:...+` lines, **make sure** that it contains a paragraph not a `+` block.
* Change the inner items to either `part::` or something Metanorma understands (which I don't know what will work, so you have to try)

And please try compiling the document. Thanks.

2024-07-28 19:55 UTC, anermina commented
@ronaldtse Markup was incorrect here.

Instead of 
````
statement::
+
--
text
--
````
we should use
````
[statement]
--
text
--
````

Fixing this.

2024-07-28 23:34 UTC, anermina commented
It seems tables are not supported in the requirement blocks. This causes crashing.

Example of the requirement that refers to a table:
![image](https://github.com/user-attachments/assets/bbab88a5-1ccd-42e4-89ba-0181dc2c9c4f)

All the tables that were included in the requirement blocks are now set outside of the blocks (below them) in order to prevent crashing.

Non-existing cross-references in the requirement blocks also cause crashing.

I wasn't able to compile the document even before any of the changes I made, so I thought there was some issue with my environment (this is still possible).
Investigating further.

2024-07-29 06:55 UTC, ronaldtse approved these changes

2024-07-30 03:01 UTC, merged

2024-08-02 12:04 UTC, opoudjis commented
@anermina The real issue was that you were providing Modspec markup, but the markup did not explicitly indicate that this was a Modspec requirement, because only OGC treats Modspec as its default. I've just made Modspec the default, as accepted by MLIT; so you should be able to revert the workarounds you did here as of next release (Monday).

2024-08-03 14:40 UTC, opoudjis commented
> Non-existing cross-references in the requirement blocks also cause crashing

I've just run into that. I'm going to work around it.

2024-08-06 22:12 UTC, anermina commented
> @anermina The real issue was that you were providing Modspec markup, but the markup did not explicitly indicate that this was a Modspec requirement, because only OGC treats Modspec as its default. I've just made Modspec the default, as accepted by MLIT; so you should be able to revert the workarounds you did here as of next release (Monday).
> 
> ... There may well be other issues causing crashes, but changing the default to Modspec will address a lot of this.

Thank you, @opoudjis !
I thought the default is MRR and I was referring to [the documentation from metanorma.org](https://www.metanorma.org/author/topics/blocks/requirements-mrr/).
![image](https://github.com/user-attachments/assets/ce96dfce-4493-4b7c-911d-7be37858c9c5)

Does this mean MRR was not used by default?

2024-08-07 03:41 UTC, opoudjis commented
So, to clarify:

MRR *is* the default. Modspec is only the default in OGC (and now Plateau).

The issue is, that "statement" as a component type is not part of MRR, but is specific to Modspec. MRR does not recognise it as a component type, which is why MRR was shoving its content into a classification, and not dealing with the blocks in it. (The only MRR catch-all for a piece of prose is "description".)

2024-08-07 06:45 UTC, anermina commented
Thank you for clarifying, @opoudjis !

The following example has caused confusion because it uses "statement" under MRR documentation.
![image](https://github.com/user-attachments/assets/dae977de-b2c2-47ca-bfe8-8db666700992)

I will replace "statement" with "specification" in this example.

2024-08-07 12:09 UTC, opoudjis commented
Thank you, my apologies if it was me. (It likely was.)